"""Free, white-box honesty ATTESTATION — dogfoods styxx's SHIPPED single-pass gate on local Qwen-3B
data we already have. No API. Emits the EU AI Act Article 15.1(a) attestation document for the
detect-and-abstain honesty layer, with measured HELD-OUT CATCH/PRESERVE per task regime + the limit
map (including the API-pending retrieval tier). The OpenAI two-signal version
(PREREG_honesty_layer_deployment) is the stronger tier, pending credit; this is the $0 deliverable.
"""
from __future__ import annotations
import json, os, random, sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(os.path.dirname(HERE)))   # repo root -> import styxx
from styxx.single_pass import calibrate_single_pass          # the SHIPPED primitive we attest


def load_rows(fname, ent_key, ok_key):
    d = json.load(open(os.path.join(HERE, fname), encoding="utf-8"))
    rows = d.get("rows", d)
    return [(float(r[ent_key]), bool(r[ok_key])) for r in rows if ent_key in r and ok_key in r]


def evaluate(rows, seed=0):
    rnd = random.Random(seed)
    idx = list(range(len(rows))); rnd.shuffle(idx)
    cut = int(0.7 * len(idx))
    tr = [rows[i] for i in idx[:cut]]
    te = [rows[i] for i in idx[cut:]]
    cal = calibrate_single_pass([e for e, ok in tr if not ok], [e for e, ok in tr if ok])
    thr = cal.entropy_threshold
    w = [e for e, ok in te if not ok]
    r = [e for e, ok in te if ok]
    catch = (sum(1 for e in w if e >= thr) / len(w)) if w else None
    preserve = (sum(1 for e in r if e < thr) / len(r)) if r else None
    return {"n": len(rows), "gate_auc": round(cal.auc, 3), "threshold": round(thr, 3),
            "n_test_wrong": len(w), "n_test_right": len(r),
            "CATCH": round(catch, 3) if catch is not None else None,
            "PRESERVE": round(preserve, 3) if preserve is not None else None}


REGIMES = [
    ("derivation (arithmetic)", "honesty_scaling_result_Qwen2_5-3B-Instruct.json", "entropy", "ok"),
    ("factual recall (TriviaQA)", "residuals_meta.json", "entropy", "correct"),
]
results = {}
for name, f, ek, ok in REGIMES:
    try:
        rows = load_rows(f, ek, ok)
        results[name] = evaluate(rows) if rows else {"error": "no rows"}
    except Exception as e:
        results[name] = {"error": repr(e)}
    print(name, "->", results[name])

json.dump({"model": "Qwen2.5-3B-Instruct", "gate": "styxx.single_pass calibrate_single_pass (held-out)",
           "regimes": results}, open(os.path.join(HERE, "whitebox_attestation_result.json"), "w"), indent=2)


def row(name, m):
    if "error" in m:
        return f"| {name} | — | — | — | {m['error']} |"
    return (f"| {name} | {m['gate_auc']} | {m['CATCH']} | {m['PRESERVE']} | "
            f"{m['n_test_wrong']}w/{m['n_test_right']}r |")


att = f"""# styxx Honesty-Layer Attestation — white-box tier — Qwen2.5-3B-Instruct
*EU AI Act Article 15.1(a) receipt. Generated by styxx's shipped single-pass detect-and-abstain gate
(`calibrate_single_pass` + entropy threshold), held-out. No external API. Falsifiable, public receipts.*

- **System under attestation:** Qwen2.5-3B-Instruct (white-box, local)
- **Honesty layer:** `styxx.single_pass` detect-and-abstain — flags a confabulation when the clean
  first-token entropy at the moment of commitment exceeds a per-model calibrated threshold, and abstains.
- **Method:** threshold calibrated on a 70% train split, **CATCH / PRESERVE measured on the held-out 30%.**

## Measured operating points (held-out)

| task regime | gate AUC | CATCH (errors flagged) | PRESERVE (correct spared) | n_test |
|---|---|---|---|---|
{row(REGIMES[0][0], results[REGIMES[0][0]])}
{row(REGIMES[1][0], results[REGIMES[1][0]])}

CATCH = P(abstain | wrong); PRESERVE = P(answer kept | correct), at the Youden-optimal threshold.

## Limit map (part of the attestation, not a footnote)

- **Power gradient (disclosed):** the gate is strong on *derivation* (unstable confabulation the model
  is internally uncertain about) and weaker on *factual recall* (the model is unconfident even when
  right). The AUCs above disclose this; do not read one regime as the other.
- **Blind to confident shared misconceptions.** A stable false belief the model holds with full
  confidence is not caught by any output-level signal (confirmed: `FINDING_residual_confab_strict` —
  even the representation does not beat the output here). The **two-signal retrieval tier**
  (`styxx.audit_claim(verify_retrieval=True)`, `PREREG_honesty_layer_deployment`) covers these — it is
  the stronger tier and is **PENDING (requires API credit)**.
- **Belief-not-truth; detect-and-abstain, corrects nothing; single model, single-vendor calibration.**

## Receipt chain (the falsifiable findings this attestation rests on — all public)

- signal-locus law **SURVIVED** — span > first-token, gap grows with capability (`FINDING_honesty_signal_locus`)
- first-token scaling **REPORT_AS_LANDED** — calibration flat, difficulty confound (`FINDING_honesty_scaling_law`)
- self-audit on Claude **REPORT_AS_LANDED** — calibrated (Brier 0.11), honest (`FINDING_self_audit`)
- residual probe **VOID** — representation does not beat the output (`FINDING_residual_confab_strict`)
- public ledger: github.com/fathom-lab/styxx (papers/grounded-honesty-axis), commits afe9123 / 108ad88 / 46ed1e1

*A standard you can fail, that its authors fail in public and report. The two-signal tier upgrades CATCH
on the misconception wall and lands the moment the API is funded.*
"""
open(os.path.join(HERE, "attestation_whitebox.md"), "w", encoding="utf-8").write(att)
print("\nwrote whitebox_attestation_result.json + attestation_whitebox.md")
